// Agent header for calc.tsu
// Generated by Tau language

#ifndef CALC_AGENT_H
#define CALC_AGENT_H

class calcAgent {
public:
calcAgent();
void start();
void stop();
bool isRunning();
private:
bool running;
// Async execution context
};

#endif // CALC_AGENT_H
