// Agent header for test.tsu
// Generated by Tau language

#ifndef TEST_AGENT_H
#define TEST_AGENT_H

class testAgent {
public:
testAgent();
void start();
void stop();
bool isRunning();
private:
bool running;
// Async execution context
};

#endif // TEST_AGENT_H
